#!/bin/bash

function start() {
	# staging
	git add -A
	
	# commit
	printf "input commit message.\n> "
	read -r commitmsg
	if [ -z "$commitmsg" ]; then
		commitmsg="update"
	fi
	git commit -m "$commitmsg"

	# pull
	echo "select pull branch."
	sleep 0.5
	git branch | fzf | read branch
	git pull origin $branch

	# push
	git push origin head
}

if [ -e "$PWD/.git" ]; then
	start
else
	echo "this dir is not git project."
fi

